Error handing (#69)
* do not echo template

* add

* add exit handler

* add exit handler

* add exit handler

* add paramter for print template

* add errorTargets

* add errorTargets

* add template to name

* add errorHandling

diff --git a/deployment/base-template/orchestration-job.yml b/deployment/base-template/orchestration-job.yml
--- a/deployment/base-template/orchestration-job.yml
+++ b/deployment/base-template/orchestration-job.yml
@@ -4,6 +4,7 @@ metadata:
   name: orchestration-job-template
   namespace: clusterscanner
 spec:
+  onExit: exit-handler
   activeDeadlineSeconds: 21600 # 6h
   entrypoint: main # Entry point for job execution
   workflowSpec:
@@ -30,6 +31,7 @@ spec:
       - workflow.parameters.allResultsGitTarget
       - workflow.parameters.imageRegistryBase
       - workflow.parameters.clusterImageScannerImageTag
+      - workflow.parameters.errorTargets
 
   templates:
     - name: main
@@ -171,6 +173,12 @@ spec:
             value: "{{ workflow.parameters.imageRegistryBase }}"
           - name: clusterImageScannerImageTag
             value: "{{ workflow.parameters.clusterImageScannerImageTag }}"
+          - name: "slackTokenSecretName"
+            value: "{{ workflow.parameters.slackTokenSecretName }}"
+          - name: errorTargets
+            value: "{{ workflow.parameters.errorTargets }}"
+          - name: IS_PRINT_TEMPLATE
+            value: "true" # TODO false
 
     - name: notify-teams
       volumes:
@@ -752,4 +760,103 @@ spec:
             #  --silent \
             #  --show-error \
             #  "${DEPENDENCY_TRACK_URL}/api/v1/project"
+          done
+
+    - name: exit-handler
+      script:
+        command: [/bin/bash]
+        resources:
+          limits:
+            cpu: '1'
+            memory: 128Mi
+          requests:
+            cpu: '0.2'
+            memory: 128Mi
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          readOnlyRootFilesystem: false
+          runAsNonRoot: true
+          runAsUser: 1001
+        image: "{{ workflow.parameters.imageRegistryBase }}/cluster-image-scanner-notifier:{{ workflow.parameters.clusterImageScannerImageTag }}"
+        imagePullPolicy: Always # TODO IfNotPresent
+        env:
+          - name: MESSAGE_TARGETS
+            value: "{{ workflow.parameters.errorTargets }}"
+          - name: SLACK_CLI_TOKEN
+            valueFrom:
+              secretKeyRef:
+                name: "{{ workflow.parameters.slackTokenSecretName }}"
+                key: SLACK_CLI_TOKEN
+
+        envFrom:
+          - configMapRef:
+              name: "scanjob-env-parameter"
+        source: |
+          if [ "${MESSAGE_TARGETS}" == "" ]; then
+            echo "MESSAGE_TARGETS set, exiting"
+            exit 1
+          fi
+          
+          failures='{{workflow.failures}}'
+          failures=$(echo "${failures:1:-1}" | sed 's#\\"#"#g')
+          sendMessageViarocketchat() {
+            channel="${1}"
+            message="${2}"
+          
+            message=$(echo "${failures}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
+            echo "{\"channel\": \"${channel}\", \"author_name\": \"ClusterImageScanner\", \"blocks\": ${message}}" > /tmp/slack-template.json
+          
+            if [ "${ROCKET_CHAT_USER_ID}" == "" ]; then # ROCKET_CHAT_USER_ID comes from cm scanjob-parameter
+              echo "No ROCKET_CHAT_USER_ID set"
+              exit 3
+            fi
+            if [ "${SLACK_CLI_TOKEN}" == "" ]; then
+              echo "No SLACK_CLI_TOKEN set"
+              exit 2
+            fi
+          
+            echo "Sending to rocketchat ${SLACK_MESSAGE_ENDPOINT} ${channel}"
+            curl -H "Content-type: application/json" \
+              -d @/tmp/slack-template.json \
+              -H "X-Auth-Token: ${SLACK_CLI_TOKEN}" \
+              -H "X-User-Id: ${ROCKET_CHAT_USER_ID}" \
+              -X POST \
+              "${SLACK_MESSAGE_ENDPOINT}"
+          }
+          sendMessageViaslack() {
+            channel="${1}"
+          
+            message=$(echo "${failures}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
+            echo "{\"channel\": \"${channel}\", \"author_name\": \"ClusterImageScanner\", \"blocks\": ${message}}" > /tmp/slack-template.json
+            cat /tmp/slack-template.json
+          
+            if [ "${SLACK_CLI_TOKEN}" == "" ]; then
+              echo "No SLACK_CLI_TOKEN set"
+              exit 2
+            fi
+          
+            curl \
+              -H "Content-type:application/json" \
+              -H "Authorization: Bearer ${SLACK_CLI_TOKEN}" \
+              -X POST \
+              -d @/tmp/slack-template.json \
+              "${SLACK_MESSAGE_ENDPOINT}"
+          }
+          
+          fn_exists() { declare -F "$1" > /dev/null; }
+          
+          echo "${MESSAGE_TARGETS}" |  jq -c '.[]' | while read i; do
+            channel=$(echo "${i}" | jq -r '.channel')
+            type=$(echo "${i}" | jq -r '.type')
+            echo "Sending via ${type} to channel ${channel}"
+            toCall="sendMessageVia$type"
+            if ! fn_exists ${toCall} ; then
+              echo "Message type '${type}' doesn't exit"
+              exit 1
+            fi
+
+            ${toCall} "${channel}"
           done
diff --git a/deployment/base-template/scanjob.yml b/deployment/base-template/scanjob.yml
--- a/deployment/base-template/scanjob.yml
+++ b/deployment/base-template/scanjob.yml
@@ -1,9 +1,10 @@
 apiVersion: argoproj.io/v1alpha1
 kind: WorkflowTemplate
 metadata:
-  name: scan-image-job
+  name: scan-image-job-template
   namespace: clusterscanner
 spec:
+  onExit: exit-handler
   activeDeadlineSeconds: 3600
   artifactRepositoryRef:
     configMap: artifact-repositories
@@ -20,7 +21,6 @@ spec:
       - name: DEFECTDOJO_SECRETS
       - name: SCAN_ID
       - name: team
-      - name: appname
       - name: environment
       - name: namespace
       - name: scm_source_branch
@@ -44,14 +44,10 @@ spec:
       - name: imageRegistryBase
       - name: scanjobEnvParameter
       - name: containerType
-
+      - name: slackTokenSecretName
+      - name: errorTargets
   templates:
     - name: main
-      retryStrategy:
-        limit: 1
-        retryPolicy: "Always"
-#        affinity:
-#          nodeAntiAffinity: {}
       dag:
         tasks:
           - name: imagefetcher
@@ -354,8 +350,8 @@ spec:
             value: "{{ workflow.parameters.is_scan_dependency_track }}"
           - name: APP_NAME
             value: "{{ workflow.parameters.appname }}"
-          - name: VERSION
-            value: "{{ workflow.parameters.appversion }}"
+          - name: APP_VERSION
+            value: "{{ workflow.parameters.appversion }}" # TODO Usage of image version
           - name: DD_BRANCH_NAME
             value: "{{ workflow.parameters.image }}"
           - name: NAMESPACE
@@ -383,7 +379,11 @@ spec:
             echo "Dependency Track scan is disabled"
             exit 0
           fi
-          PROJECT_NAME=$(echo "${DD_PRODUCT_NAME_TEMPLATE}" | sed "s~###ENVIRONMENT###~${ENVIRONMENT}~" | sed "s~###NAMESPACE###~${NAMESPACE}~" | sed "s~###APP_NAME###~${APP_NAME}~" )
+          
+          source ./scan-common.bash        
+          parse_and_set_image_variables
+          
+          PROJECT_NAME=$(echo "${DD_PRODUCT_NAME_TEMPLATE}" | sed "s~###ENVIRONMENT###~${ENVIRONMENT}~" | sed "s~###NAMESPACE###~${NAMESPACE}~" | sed "s~###APP_NAME###~${IMAGE_NAME}~" )
           echo "PROJECT_NAME: ${PROJECT_NAME}"
           bomPath="/clusterscanner/data/bom.json"
           exportFilePath="/clusterscanner/data/findings.json"
@@ -392,7 +392,7 @@ spec:
            exit 4
           fi
           bomBase64=$(cat "${bomPath}" | base64 -w 0)
-          echo '{ "projectName": "'${PROJECT_NAME}'", "projectVersion": "'${VERSION}'", "autoCreate": true, "bom": "'${bomBase64}'" }' > /tmp/tmpfile
+          echo '{ "projectName": "'${PROJECT_NAME}'", "projectVersion": "'${IMAGE_TAG}'", "autoCreate": true, "bom": "'${bomBase64}'" }' > /tmp/tmpfile
           curl -X "PUT" \
             "${DEPENDENCY_TRACK_URL}/api/v1/bom" \
             -H 'Content-Type: application/json' \
@@ -434,7 +434,7 @@ spec:
 
           echo "/tmp/project.json"
           cat /tmp/project.json
-          cat /tmp/project.json | jq -r '.[] | select(.version=="'${VERSION}'") | .uuid' > /tmp/project-uuid.txt
+          cat /tmp/project.json | jq -r '.[] | select(.version=="'${IMAGE_TAG}'") | .uuid' > /tmp/project-uuid.txt
 
           export UUID=$(cat /tmp/project-uuid.txt)
           if [ "${UUID}" == "" ]; then
@@ -1432,3 +1432,103 @@ spec:
           echo "Storing into /clusterscanner/data/{{ workflow.parameters.environment }}__{{ workflow.parameters.namespace }}__${IMAGE_NAME_CLEANED}--${IMAGE_HASH}"
           echo "${JSON_RESULT}"
           echo "${JSON_RESULT}"  > /clusterscanner/data/{{ workflow.parameters.environment }}__{{ workflow.parameters.namespace }}__${IMAGE_NAME_CLEANED}--${IMAGE_HASH}.json
+          
+
+    - name: exit-handler
+      script:
+        command: [/bin/bash]
+        resources:
+          limits:
+            cpu: '1'
+            memory: 128Mi
+          requests:
+            cpu: '0.2'
+            memory: 128Mi
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          readOnlyRootFilesystem: false
+          runAsNonRoot: true
+          runAsUser: 1001
+        image: "{{ workflow.parameters.imageRegistryBase }}/cluster-image-scanner-notifier:{{ workflow.parameters.clusterImageScannerImageTag }}"
+        imagePullPolicy: Always # TODO IfNotPresent
+        env: # TODO check for email creds
+          - name: MESSAGE_TARGETS
+            value: "{{ workflow.parameters.errorTargets }}"
+          - name: SLACK_CLI_TOKEN
+            valueFrom:
+              secretKeyRef:
+                name: "{{ workflow.parameters.slackTokenSecretName }}"
+                key: SLACK_CLI_TOKEN
+
+        envFrom:
+          - configMapRef:
+              name: "scanjob-env-parameter"
+        source: |         
+          if [ "${MESSAGE_TARGETS}" == "" ]; then
+            echo "MESSAGE_TARGETS set, exiting"
+            exit 1
+          fi
+          
+          failures='{{workflow.failures}}'
+          failures=$(echo "${failures:1:-1}" | sed 's#\\"#"#g')
+          sendMessageViarocketchat() {
+            channel="${1}"
+            message="${2}"
+          
+            message=$(echo "${failures}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
+            echo "{\"channel\": \"${channel}\", \"author_name\": \"ClusterImageScanner\", \"blocks\": ${message}}" > /tmp/slack-template.json
+          
+            if [ "${ROCKET_CHAT_USER_ID}" == "" ]; then # ROCKET_CHAT_USER_ID comes from cm scanjob-parameter
+              echo "No ROCKET_CHAT_USER_ID set"
+              exit 3
+            fi
+            if [ "${SLACK_CLI_TOKEN}" == "" ]; then
+              echo "No SLACK_CLI_TOKEN set"
+              exit 2
+            fi
+          
+            echo "Sending to rocketchat ${SLACK_MESSAGE_ENDPOINT} ${channel}"
+            curl -H "Content-type: application/json" \
+              -d @/tmp/slack-template.json \
+              -H "X-Auth-Token: ${SLACK_CLI_TOKEN}" \
+              -H "X-User-Id: ${ROCKET_CHAT_USER_ID}" \
+              -X POST \
+              "${SLACK_MESSAGE_ENDPOINT}"
+          }
+          sendMessageViaslack() {
+            channel="${1}"
+          
+            message=$(echo "${failures}" | jq -r '.[] | {"type": "section","text": {"type": "mrkdwn","text": "- *name:* _ \(.displayName)_\n- *template:* _\(.templateName)_\n- *message:* _\(.message)_\n- *phase:* _\(.phase)_\n- *podName:* _\(.podName)_\n- *finishedAt:* _\(.finishedAt)_\n"}},{"type": "divider"}' | jq -s .)
+            echo "{\"channel\": \"${channel}\", \"author_name\": \"ClusterImageScanner\", \"blocks\": ${message}}" > /tmp/slack-template.json
+            cat /tmp/slack-template.json
+          
+            if [ "${SLACK_CLI_TOKEN}" == "" ]; then
+              echo "No SLACK_CLI_TOKEN set"
+              exit 2
+            fi
+          
+            curl \
+              -H "Content-type:application/json" \
+              -H "Authorization: Bearer ${SLACK_CLI_TOKEN}" \
+              -X POST \
+              -d @/tmp/slack-template.json \
+              "${SLACK_MESSAGE_ENDPOINT}"
+          }
+          
+          fn_exists() { declare -F "$1" > /dev/null; }
+          
+          echo "${MESSAGE_TARGETS}" |  jq -c '.[]' | while read i; do
+            channel=$(echo "${i}" | jq -r '.channel')
+            type=$(echo "${i}" | jq -r '.type')
+            echo "Sending via ${type} to channel ${channel}"
+            toCall="sendMessageVia$type"
+            if ! fn_exists ${toCall} ; then
+              echo "Message type '${type}' doesn't exit"
+              exit 1
+            fi
+
+            ${toCall} "${channel}"
+          done
