beautify

diff --git a/deployment/base-template/orchestration-job.yml b/deployment/base-template/orchestration-job.yml
--- a/deployment/base-template/orchestration-job.yml
+++ b/deployment/base-template/orchestration-job.yml
@@ -217,7 +217,7 @@ spec:
               echo "Sending to email ${email}"
               if [ "${smtp-auth-user}" != "USERNAME@YOURDOMAIN.COM" ] && [ "${smtp-auth-user}" != "" ]; then
                 message="$message\nimage: ${image}, app: ${appName}, namespace: ${namespace}, environment: ${environment}, link to DefectDojo: ${ddLink}"
-                echo -e "${message}" | mail -s "Found unhandled findings" "${email}" # works
+                echo -e "${message}" | mail -s "Found unhandled findings" "${email}" || echo "ERROR during sending ${message}"
               else
                 echo "Warning: email set, but no email configured"
               fi
