feat: add version

diff --git a/deployment/base-template/scanjob.yml b/deployment/base-template/scanjob.yml
--- a/deployment/base-template/scanjob.yml
+++ b/deployment/base-template/scanjob.yml
@@ -47,6 +47,7 @@ spec:
       - name: scanRootImageName
       - name: scanLifetimeImageName
       - name: scanNewVersionImageName
+      - name: scanSyftImageName
 
   templates:
     - name: main
@@ -57,14 +58,6 @@ spec:
           - name: sbom-generation
             depends: imagefetcher
             template: sbom-generation
-          # wait for https://github.com/argoproj/argo-workflows/issues/6869 to be in release
-          #            arguments:
-          #              parameters:
-          #                - name: scanSyftImageName
-          #                  valueFrom:
-          #                  configMapKeyRef:
-          #                    name: scanjob-parameter
-          #                    key: syftImageName
           - name: scan-dependency-track
             depends: sbom-generation
             template: scan-dependency-track
@@ -115,7 +108,7 @@ spec:
                 - name: results-generic-findings
                   from: "{{ tasks.results-collect-generic-findings.outputs.artifacts.results-generic-findings }}"
           - name: results-aggregate
-            depends: (results-dependency-check-dd-upload.Succeeded || results-generic-dd-upload.Succeeded)
+            depends: (results-dependency-check-dd-upload.Succeeded || results-generic-dd-upload.Succeeded || results-dependency-track-dd-upload.Succeeded)
             template: results-aggregate
             arguments:
               artifacts:
@@ -125,14 +118,20 @@ spec:
                   from: "{{ tasks.results-generic-dd-upload.outputs.artifacts.is-finding-file }}"
                 - name: results-dd-generic-findings-file
                   from: "{{ tasks.results-generic-dd-upload.outputs.artifacts.findings-file }}"
+                - name: results-generic
+                  from: "{{ tasks.results-collect-generic-findings.outputs.artifacts.results-generic }}"
                 - name: results-dd-dependency-check-test-link
                   from: "{{ tasks.results-dependency-check-dd-upload.outputs.artifacts.results-dd-dependency-check-test-link }}"
                 - name: results-dd-dependency-check-is-finding-file
                   from: "{{ tasks.results-dependency-check-dd-upload.outputs.artifacts.is-finding-file }}"
                 - name: results-dd-dependency-check-findings-file
                   from: "{{ tasks.results-dependency-check-dd-upload.outputs.artifacts.findings-file }}"
-                - name: results-generic
-                  from: "{{ tasks.results-collect-generic-findings.outputs.artifacts.results-generic }}"
+                - name: results-dd-dependency-track-test-link
+                  from: "{{ tasks.results-dependency-track-dd-upload.outputs.artifacts.results-dd-dependency-track-test-link }}"
+                - name: results-dd-dependency-track-is-finding-file
+                  from: "{{ tasks.results-dependency-track-dd-upload.outputs.artifacts.is-finding-file }}"
+                - name: results-dd-dependency-track-findings-file
+                  from: "{{ tasks.results-dependency-track-dd-upload.outputs.artifacts.findings-file }}"
               parameters:
                 - name: "dd-generic-exitcode"
                   value: "{{ tasks.results-generic-dd-upload.exitCode }}"
@@ -146,6 +145,12 @@ spec:
                   value: "{{ tasks.results-dependency-check-dd-upload.startedAt }}"
                 - name: "dd-dependency-check-finishedat"
                   value: "{{ tasks.results-dependency-check-dd-upload.finishedAt }}"
+                - name: "dd-dependency-track-exitcode"
+                  value: "{{ tasks.results-dependency-track-dd-upload.exitCode }}"
+                - name: "dd-dependency-track-startedat"
+                  value: "{{ tasks.results-dependency-track-dd-upload.startedAt }}"
+                - name: "dd-dependency-track-finishedat"
+                  value: "{{ tasks.results-dependency-track-dd-upload.finishedAt }}"
 
     - name: imagefetcher
       volumes:
@@ -173,6 +178,10 @@ spec:
             value: "{{ workflow.parameters.image }}"
           - name: IMAGE_BY_HASH
             value: "{{ workflow.parameters.image_id }}"
+          - name: SKOPEO_COPY_PARAMETER
+            value: "" # e.g. "--src-tls-verify=false "
+          - name: SKOPEO_INSPECT_PARAMETER
+            value: "" # e.g. "tls-verify=false "
         source: |
           # IMAGE_TAR_PATH from base image
           set -e
@@ -193,7 +202,7 @@ spec:
 
           echo "Checking for existing config manifest of ${IMAGE_BY_HASH}"
           # catch tagged images (which can happen if we don't know the image hash to pull by). When we have a tagged image, the image is assumed to be mutable - therefore the config.json of the image is checked, to make sure they are identical before skipping the pull process.
-          skopeo inspect --config "docker://${IMAGE_BY_HASH}" | jq -cMS 'def recursively(f): . as $in | if type == "object" then reduce keys_unsorted[] as $key ( {}; . + { ($key):  ($in[$key] | recursively(f)) } ) elif type == "array" then map( recursively(f) ) | f else . end; . | recursively(sort)' > "${config_dir}/config.json"
+          skopeo inspect ${SKOPEO_INSPECT_PARAMETER} --config "docker://${IMAGE_BY_HASH}" | jq -cMS 'def recursively(f): . as $in | if type == "object" then reduce keys_unsorted[] as $key ( {}; . + { ($key):  ($in[$key] | recursively(f)) } ) elif type == "array" then map( recursively(f) ) | f else . end; . | recursively(sort)' > "${config_dir}/config.json"
           ls -la "${config_dir}/config.json"
           if [[ -f "${IMAGE_TAR_FOLDER_PATH}/config.json" ]] && diff -qs "${config_dir}/config.json" "${IMAGE_TAR_FOLDER_PATH}/config.json" && [ -f ${IMAGE_TAR_FOLDER_PATH}/docker-archive-image.tar ]; then
             echo "Already got image with identical config manifest, skipping"
@@ -204,9 +213,9 @@ spec:
 
           echo "Downloading image ${IMAGE_BY_HASH} to ${image_copy_dir}"
 
-          skopeo copy "docker://${IMAGE_BY_HASH}" "dir:${image_copy_dir}/"
+          skopeo copy ${SKOPEO_COPY_PARAMETER} "docker://${IMAGE_BY_HASH}" "dir:${image_copy_dir}/"
           rm -Rf ${IMAGE_TAR_FOLDER_PATH}/docker-archive-image.tar || true
-          skopeo copy "docker://${IMAGE_BY_HASH}" "docker-archive:${IMAGE_TAR_FOLDER_PATH}/docker-archive-image.tar"
+          skopeo copy ${SKOPEO_COPY_PARAMETER} "docker://${IMAGE_BY_HASH}" "docker-archive:${IMAGE_TAR_FOLDER_PATH}/docker-archive-image.tar"
           layers=$(jq -r '.layers' "${image_copy_dir}/manifest.json")
           if [ "${layers}" != "null" ] && [ "${layers}" != "" ]; then
             extractionCommand=".layers | .[].digest"
@@ -251,11 +260,8 @@ spec:
           - name: sbom
             path: /clusterscanner/data/bom.json
             archiveLogs: true
-#      inputs:
-#        parameters:
-#          - name: scanSyftImageName
       container:
-        image: "anchore/syft"
+        image: "{{ workflow.parameters.scanSyftImageName }}"
         command: ["/syft"]
         args: [
             "packages",
@@ -312,20 +318,52 @@ spec:
             subPath: "results/{{ workflow.parameters.image_id }}/sbom"
         source: |
           set -e
-          export bomBase64=$(cat /clusterscanner/data/bom.json | base64 -w 0)
-          echo '{ "projectName": "'${PROJECT_NAME}'", "projectVersion": "'${VERSION}'", "autoCreate": true, "bom": "'${bomBase64}'" }' > /tmp/tmpdata
-          echo '{ "projectName": "'${PROJECT_NAME}'", "projectVersion": "'${VERSION}'" }'
-          curl -X "PUT" "${DEPENDENCY_TRACK_URL}/api/v1/bom" \
+          bomPath="/clusterscanner/data/bom.json"
+          exportFilePath="/clusterscanner/data/findings.json"
+          if [ "${DEPENDENCY_TRACK_KEY}" == "" ]; then
+           echo "Error: DEPENDENCY_TRACK_KEY not set"
+           exit 4
+          fi
+          bomBase64=$(cat "${bomPath}" | base64 -w 0)
+          echo '{ "projectName": "'${PROJECT_NAME}'", "projectVersion": "'${VERSION}'", "autoCreate": true, "bom": "'${bomBase64}'" }' > /tmp/tmpfile
+          curl -X "PUT" \
+            "${DEPENDENCY_TRACK_URL}/api/v1/bom" \
             -H 'Content-Type: application/json' \
             -H "X-API-Key: ${DEPENDENCY_TRACK_KEY}" \
-            -d @/tmp/tmpdata
-          echo "GET ${DEPENDENCY_TRACK_URL}/api/v1/project?name=${PROJECT_NAME}"
+            -d @/tmp/tmpfile \
+            --silent \
+            --show-error \
+            --output /tmp/token.json
+          token=$(cat /tmp/token.json | jq -r '.token')
 
-          nameParameterUrlEncoded=$(printf %s  "name=${PROJECT_NAME}" | jq -sRr @uri)
-          curl "${DEPENDENCY_TRACK_URL}/api/v1/project?${nameParameterUrlEncoded}" \
+          counter=0
+          processingPerformed="false"
+          MAX_RETRIES=60
+          while [ "${processingPerformed}" == "true" ]; do
+           let counter=counter+1
+           url="${DEPENDENCY_TRACK_URL}/api/v1/bom/token/${token}"
+           echo "Fetching $url"
+           processingPerformed=$(curl ${url} \
             --header 'Accept: application/json' \
             -H "X-API-Key: ${DEPENDENCY_TRACK_KEY}" \
-            --output /tmp/project.json
+            --silent \
+            --show-error \
+           | jq '.processing')
+           echo "Processing status '${processingPerformed}' from Dependency Track"
+           if [ ${counter} -gt ${MAX_RETRIES} ]; then
+             echo "ERROR Reached maximum retries of ${MAX_RETRIES}, stop trying to get processing status"
+             exit 2
+           fi
+           sleep 2
+          done
+          echo "GET ${DEPENDENCY_TRACK_URL}/api/v1/project?name=${PROJECT_NAME}&.."
+          nameParameterUrlEncoded=$(printf %s "${PROJECT_NAME}" | jq -sRr @uri)
+          curl "${DEPENDENCY_TRACK_URL}/api/v1/project?name=${nameParameterUrlEncoded}" \
+           --silent \
+           --show-error \
+           --header 'Accept: application/json' \
+           -H "X-API-Key: ${DEPENDENCY_TRACK_KEY}" \
+           --output /tmp/project.json
 
           echo "/tmp/project.json"
           cat /tmp/project.json
@@ -333,20 +371,26 @@ spec:
 
           export UUID=$(cat /tmp/project-uuid.txt)
           if [ "${UUID}" == "" ]; then
-            echo "Error: UUID has the unexpceted value '${UUID}'"
-            exit 1
+           echo "Error: UUID has the unexpceted value '${UUID}'"
+           exit 1
           fi
           if [ $(echo "${UUID}" | wc -l) -ne 1 ]; then
-            echo "Error: UUID '${UUID}' has unexpected newline"
-            exit 3
+           echo "Error: UUID '${UUID}' has unexpected newline"
+           exit 3
           fi
 
-
           echo "Fetching ${DEPENDENCY_TRACK_URL}/api/v1/finding/project/${UUID}/export"
-          curl "${DEPENDENCY_TRACK_URL}/api/v1/finding/project/${UUID}/export" \
-            -H "X-API-Key: ${DEPENDENCY_TRACK_KEY}" --output /clusterscanner/data/findings.json
-          echo "Findings"
-          cat /clusterscanner/data/findings.json
+
+
+          purl="^(?:(?!pkg:deb).)*$"
+          purl="pkg:maven.*"
+          purlEncodedValue=$(printf %s "${purl}" | jq -sRr @uri)
+          curl -v "${DEPENDENCY_TRACK_URL}/api/v1/finding/project/${UUID}/export?purl=${purlEncodedValue}" \
+           --silent \
+           --show-error \
+           -H "X-API-Key: ${DEPENDENCY_TRACK_KEY}" \
+           --output ${exportFilePath}
+
 
 
     - name: results-dependency-track-dd-upload
@@ -356,7 +400,7 @@ spec:
             claimName: cluster-image-scanner-scandata
       outputs:
         artifacts:
-          - name: results-dd-dependency-check-test-link
+          - name: results-dd-dependency-track-test-link
             path: /code/defectDojoTestLink.txt
           - name: is-finding-file
             path: /code/isFinding
@@ -813,20 +857,26 @@ spec:
     - name: results-aggregate
       inputs:
         artifacts:
-          - name: results-dd-dependency-check-test-link
-            path: /tmp/dd-dependency-check-test-link.txt
           - name: results-dd-generic-test-link
             path: /tmp/dd-generic-test-link.txt
           - name: results-dd-generic-is-finding-file
             path: /tmp/isFinding-generic
           - name: results-dd-generic-findings-file
             path: /tmp/findings-generic.json
+          - name: results-generic
+            path: /tmp/result.json
+          - name: results-dd-dependency-check-test-link
+            path: /tmp/dd-dependency-check-test-link.txt
           - name: results-dd-dependency-check-is-finding-file
             path: /tmp/isFinding-dependency-check
           - name: results-dd-dependency-check-findings-file
             path: /tmp/findings-dependency-check.json
-          - name: results-generic
-            path: /tmp/result.json
+          - name: results-dd-dependency-track-test-link
+            path: /tmp/dd-dependency-track-test-link.txt
+          - name: results-dd-dependency-track-is-finding-file
+            path: /tmp/isFinding-dependency-track
+          - name: results-dd-dependency-track-findings-file
+            path: /tmp/findings-dependency-track.json
         parameters:
           - name: dd-generic-exitcode
           - name: dd-generic-startedat
@@ -834,6 +884,9 @@ spec:
           - name: dd-dependency-check-exitcode
           - name: dd-dependency-check-startedat
           - name: dd-dependency-check-finishedat
+          - name: dd-dependency-track-exitcode
+          - name: dd-dependency-track-startedat
+          - name: dd-dependency-track-finishedat
       volumes:
         - name: scandata
           persistentVolumeClaim:
@@ -864,6 +917,39 @@ spec:
           JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM '.slack = "{{ workflow.parameters.slack }}"')
           JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM '.email = "{{ workflow.parameters.email }}"')
           JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM '.appname = "{{ workflow.parameters.appname }}"')
+
+          JSON_DD_DEPENDENCY_TRACK=$(echo "{\"errors\":[]}" | jq -Sc ".+= {\"startedAt\": \"{{ inputs.parameters.dd-dependency-track-startedat }}\"}")
+          isFinding=$(cat /tmp/isFinding-dependency-track) || isFinding="false"
+          if [ "$isFinding" == "true" ]; then
+            DD_LINK=$(cat /tmp/dd-dependency-track-test-link.txt)
+            JSON_DD_DEPENDENCY_TRACK=$(echo ${JSON_DD_DEPENDENCY_TRACK} | jq -Sc ". += {\"status\": \"completed\", \"finding\": true, \"infoText\": \"Potential unhandled known vulnerabilities found in image\", \"ddLink\": \"${DD_LINK}\"}")
+            if [ $(cat /tmp/findings-dependency-track.json | wc -c) -gt 5 ]; then
+              echo "Starting DepCheck Aggregate"
+              echo $JSON_DD_DEPENDENCY_TRACK > /tmp/dd-deptrack.json
+              FILESIZE=$(stat -c%s "/tmp/findings-dependency-track.json")
+              FILESIZE_LIMT=25600 # 20kb
+              if [ $FILESIZE -lt $FILESIZE_LIMT ]; then
+                echo "Filesize of $FILESIZE is lt $FILESIZE_LIMT for /tmp/findings-dependency-track.json"
+                JSON_DD_DEPENDENCY_TRACK=$(jq '.findings += input'  /tmp/dd-deptrack.json /tmp/findings-dependency-track.json)
+              else
+                echo "Filesize of $FILESIZE is gt $FILESIZE_LIMT /tmp/findings-dependency-track.json"
+                echo '[{ "title": "Dependency Track Finding", "description": "OWASP Dependency Track found some findings, please check DefectDojo" }]' > /tmp/findings-dependency-track-zero.json
+                JSON_DD_DEPENDENCY_TRACK=$(jq '.findings += input'  /tmp/dd-deptrack.json /tmp/findings-dependency-track-zero.json)
+              fi
+            else
+              JSON_DD_DEPENDENCY_TRACK=$(echo ${JSON_DD_DEPENDENCY_TRACK} | jq -Sc ". += {\"findings\": []}")
+              echo "Warning: /tmp/findings-dependency-track.json is empty"
+            fi
+          elif [ "xX{{ inputs.parameters.dd-dependency-track-exitcode }}" != "xX0" ]; then
+            echo "Exit code != 0"
+            JSON_DD_DEPENDENCY_TRACK=$(echo ${JSON_DD_DEPENDENCY_TRACK} | jq -Sc ". += {\"status\": \"failed\", \"finding\": false, \"infoText\": \"Uploading report to DefectDojo failed.\", \"findings\": []}")
+          else
+            JSON_DD_DEPENDENCY_TRACK=$(echo ${JSON_DD_DEPENDENCY_TRACK} | jq -Sc ". += {\"status\": \"completed\", \"finding\": false, \"ddLink\": \"${DD_LINK}\", \"findings\": []}")
+          fi
+          JSON_DD_DEPENDENCY_TRACK=$(echo ${JSON_DD_DEPENDENCY_TRACK} | jq -Sc ". += {\"finishedAt\": \"{{ inputs.parameters.dd-dependency-track-finishedat }}\"}")
+          JSON_DD_DEPENDENCY_TRACK=$(echo ${JSON_DD_DEPENDENCY_TRACK} | jq -Sc ". += {\"scanType\": \"Dependency Track\"}")
+
+
 
           JSON_DD_DEPENDENCY_CHECK=$(echo "{\"errors\":[]}" | jq -Sc ".+= {\"startedAt\": \"{{ inputs.parameters.dd-dependency-check-startedat }}\"}")
           isFinding=$(cat /tmp/isFinding-dependency-check) || isFinding="false"
@@ -906,7 +992,7 @@ spec:
               echo $JSON_DD_GENERIC> /tmp/generic.json
               JSON_DD_GENERIC=$(jq '.findings += input'  /tmp/generic.json /tmp/findings-generic.json)
             else
-              JSON_DD_GENERIC=$(echo ${JSON_DD_DEPENDENCY_CHECK} | jq -Sc ". += {\"findings\": []}")
+              JSON_DD_GENERIC=$(echo ${JSON_DD_DEPENDENCY_GENERIC} | jq -Sc ". += {\"findings\": []}")
               echo "Warning: /tmp/finding-generic  is empty"
             fi
           elif [ "xX{{ inputs.parameters.dd-generic-exitcode }}" != "xX0" ]; then
@@ -916,11 +1002,14 @@ spec:
           fi
           JSON_DD_GENERIC=$(echo ${JSON_DD_GENERIC} | jq -Sc ". += {\"finishedAt\": \"{{ inputs.parameters.dd-generic-finishedat }}\"}")
           JSON_DD_GENERIC=$(echo ${JSON_DD_GENERIC} | jq -Sc ". += {\"scanType\": \"Generic\"}")
-          echo ".uploadResults += [{\"ddGenericUpload\": ${JSON_DD_GENERIC}}, {\"ddDependencyCheckUpload\": ${JSON_DD_DEPENDENCY_CHECK}}]"
-          JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM ".uploadResults += [{\"ddGenericUpload\": ${JSON_DD_GENERIC}}, {\"ddDependencyCheckUpload\": ${JSON_DD_DEPENDENCY_CHECK}}]")
+
+          uploadResults="[{\"ddGenericUpload\": ${JSON_DD_GENERIC}}, {\"ddDependencyCheckUpload\": ${JSON_DD_DEPENDENCY_CHECK}}, {\"ddDependencyTrackUpload\": ${JSON_DD_DEPENDENCY_TRACK}}]"
+          echo "uploadResults: ${uploadResults}"
+          JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM ".uploadResults += ${uploadResults}")
           DD_DEPENDENCY_CHECK_FINDING=$(echo "${JSON_RESULT}" | jq -ScM ".uploadResults[] | select(.ddDependencyCheckUpload) | .ddDependencyCheckUpload.finding")
+          DD_DEPENDENCY_TRACK_FINDING=$(echo "${JSON_RESULT}" | jq -ScM ".uploadResults[] | select(.ddDependencyTrackUpload) | .ddDependencyTrackUpload.finding")
           DD_GENERIC_FINDING=$(echo "${JSON_RESULT}" | jq -ScM ".uploadResults[] | select(.ddGenericUpload) | .ddGenericUpload.finding")
-          if [ "xX${DD_DEPENDENCY_CHECK_FINDING}" == "xXtrue" ] || [ "xX${DD_GENERIC_FINDING}" == "xXtrue" ]; then
+          if [ "xX${DD_DEPENDENCY_CHECK_FINDING}" == "xXtrue" ] || [ "xX${DD_GENERIC_FINDING}" == "xXtrue" ] || [ "xX${DD_DEPENDENCY_TRACK_FINDING}" == "xXtrue" ]; then
             JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM ".notificationRequired = true")
           else
             JSON_RESULT=$(echo "${JSON_RESULT}" | jq -ScM ".notificationRequired = false")
