cleanup

diff --git a/deployment/base-template/scanjob.yml b/deployment/base-template/scanjob.yml
--- a/deployment/base-template/scanjob.yml
+++ b/deployment/base-template/scanjob.yml
@@ -1131,7 +1131,6 @@ spec:
           
           JSON_RESULTS=$(echo "{}" | jq -Sc '.+= {"scanResults": []}')
           find /tmp/results
-          #echo 'Date,Title,CweId,Url,Severity,Description,Mitigation,Impact,References,Active,Verified' > /tmp/findings.csv
           echo '{ "findings": [] }' > /tmp/findings.json
           cat /tmp/findings.json
           ls -la /tmp/results/**/*.json
@@ -1147,55 +1146,52 @@ spec:
           for j in $(ls /tmp/results/**/*.json | grep -v "module_"); do
             echo "Collecting ${j}"
             if [ -s "${j}" ]; then
-              echo "Will replace placeholder IMAGE {{ workflow.parameters.image }} in /tmp/findings.json and /tmp/result.json"
-              #sed -i "s\###IMAGE###\{{ workflow.parameters.image }}\g" /tmp/findings.csv
+              echo "Will replace placeholder IMAGE {{ workflow.parameters.image }} in ${j}"
               echo $(jq \
                 --arg image {{ workflow.parameters.image }} \
                 '.findings[].description.image = $image ' \
-                /tmp/findings.json) > /tmp/findings.json
-              sed -i "s\###IMAGE###\{{ workflow.parameters.image }}\g" /tmp/result.json
-              echo "cat /tmp/findings.json2"
-              cat /tmp/findings.json
-              echo "Will replace placeholder CLUSTER in /tmp/findings.json and /tmp/result.json"
-              #sed -i "s/###CLUSTER###/{{ workflow.parameters.environment }}/g" /tmp/findings.csv
+                ${j}) > /tmp/finding.tmp
+
+              echo "Will replace placeholder environment in /tmp/finding.tmp"
               echo $(jq \
                 --arg cluster {{ workflow.parameters.environment }} \
                 '.findings[].description.cluster = $cluster ' \
-                /tmp/findings.json) > /tmp/findings.json
-              sed -i "s/###CLUSTER###/{{ workflow.parameters.environment }}/g" /tmp/result.json
+                /tmp/finding.tmp) > /tmp/finding.tmp
     
-              echo "Will replace placeholder NAMESPACE in /tmp/findings.json and /tmp/result.json"
-              #sed -i "s/###NAMESPACE###/{{ workflow.parameters.namespace }}/g" /tmp/findings.csv
+              echo "Will replace placeholder NAMESPACE in /tmp/finding.tmp"
               echo $(jq \
                 --arg namespace {{ workflow.parameters.namespace }} \
                 '.findings[].description.namespace = $namespace ' \
-                /tmp/findings.json) > /tmp/findings.json
-              sed -i "s/###NAMESPACE###/{{ workflow.parameters.namespace }}/g" /tmp/result.json
-    
-              #sed -i "s-###DATE###-$DATE-g" /tmp/findings.csv
-              echo "cat /tmp/findings.json1"
-              cat /tmp/findings.json 
+                /tmp/finding.tmp) > /tmp/finding.tmp
+
               echo $(jq \
                 --arg date "{$DATE}" \
                 '.findings[].date = $date' \
-                /tmp/findings.json) > /tmp/findings.json
-              sed -i "s-###DATE###-$DATE-g" /tmp/result.json
-                      
-              desc=$(jq '.findings[].description | to_entries | map(.value) | join("\n")' "${j}")
-              echo $(jq --arg desc "${desc}" '.findings[].description = ($desc | fromjson)' < "${j}") > "${j}"
+                /tmp/finding.tmp) > /tmp/finding.tmp
+              echo "/tmp/finding.tmp before desc"
+              cat /tmp/finding.tmp
+              desc=$(jq '.findings[].description | to_entries | map(.value) | join("\n")' "/tmp/finding.tmp")
+              echo $(jq --arg desc "${desc}" '.findings[].description = ($desc | fromjson)' < "/tmp/finding.tmp") > "/tmp/finding.tmp"
               cat "${j}"
-              echo $(jq --argfile f1 /tmp/findings.json --argfile f2 "${j}" -n '$f1 + $f2 | .findings = $f1.findings + $f2.findings') > /tmp/findings.json
+              echo $(jq --argfile f1 /tmp/findings.json --argfile f2 "/tmp/finding.tmp" -n '$f1 + $f2 | .findings = $f1.findings + $f2.findings') > /tmp/findings.json
             else
               echo "Error: ${j} is empty"
             fi  
 
-            if ! [ -s /tmp/findings.json ]; then
-              echo "Error: /tmp/findings.json is empty"
+            if ! [ -s ${j} ]; then
+              echo "Error: ${j} is empty"
             fi
-            echo "################################ /tmp/findings.json"
-            cat /tmp/findings.json
           done
+          
+          echo "Writing JSON_RESULTS to /tmp/result.json"
           echo "${JSON_RESULTS}" > /tmp/result.json
+          sed -i "s-###DATE###-$DATE-g" /tmp/result.json
+          echo "Will replace placeholder CLUSTER in /tmp/result.json"
+          sed -i "s/###CLUSTER###/{{ workflow.parameters.environment }}/g" /tmp/result.json
+          echo "Will replace placeholder IMAGE {{ workflow.parameters.image }} in /tmp/result.json"
+          sed -i "s\###IMAGE###\{{ workflow.parameters.image }}\g" /tmp/result.json
+          echo "Will replace placeholder NAMESPACE in/tmp/result.json"
+          sed -i "s/###NAMESPACE###/{{ workflow.parameters.namespace }}/g" /tmp/result.json
 
           echo "cat /tmp/findings.json"
           cat /tmp/findings.json
