fix: cleanup

diff --git a/deployment/base/cleanup-unpacked.yml b/deployment/base/cleanup-unpacked.yml
--- a/deployment/base/cleanup-unpacked.yml
+++ b/deployment/base/cleanup-unpacked.yml
@@ -37,11 +37,14 @@ spec:
 
             KEEP_FILE_DAYS=7
 
-            echo "Delete files /clusterscanner/images accessed more than $KEEP_FILE_DAYS before."
-            find /clusterscanner/images/ -type f -atime +$KEEP_FILE_DAYS -exec rm -f {} \; -exec echo "File {} has been deleted" \;
-            
-            echo "Will delete empty directories in /clusterscanner/images/"
-            find /clusterscanner/images/ -type d -empty -delete
+            du -sh /clusterscanner/images/ || true
+
+            for cleanupPath in $(find /clusterscanner/images/* -maxdepth 2 -mindepth 2 -mtime +${KEEP_FILE_DAYS}); do
+                echo "Removing ${cleanupPath}"
+                rm -Rf "${cleanupPath}" || echo "Error: Could not delete ${cleanupPath}"
+            done
+            find /clusterscanner/images/ -maxdepth 2 -empty -type d -delete
 
             echo "Size of /clusterscanner/images/"
             du -sh /clusterscanner/images/
+            exit 0
